import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { NavController } from '@ionic/angular';


@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage {
  Jobs : any[];
  constructor(public navCtrl: NavController) {
    this.Jobs = [{title:"Collaborateur Comptable confirmé",company:"NUMEN MADAGASCAR",contra:"Contrat CDI",description:"\n                • Tenue des dossiers : Saisie comptable, analyse les comptes, effectue les rapprochements bancaires, effectue le lettrage des comptes et rédige un compte rendu d’activités remontant toutes les incohérences…            ",details:"https://www.portaljob-madagascar.com/emploi/view/numen-madagascar-collaborateur-comptable-confirme107224"},
    {title:"Chef de Mission","company":"NUMEN MADAGASCAR",contra:"Contrat CDI","description":"\n                Responsable de la bonne réalisation des missions liées aux dossiers client qui lui sont confiées, sur les points techniques et de gestion. En lien avec le superviseur, les missions s’articulent autour…            ",details:"https://www.portaljob-madagascar.com/emploi/view/numen-madagascar-chef-de-mission107195"},
    {title:"Collaborateur Comptable débutant","company":"NUMEN MADAGASCAR","contra":"Contrat CDI","description":"\n                • Prise en charge de la saisie des écritures ou l’indexation des documents comptables • Prise en charge de la tenue des dossiers : vérifie la saisie comptable, analyse les comptes, effectue les rapprochements…            ","details":"https://www.portaljob-madagascar.com/emploi/view/numen-madagascar-collaborateur-comptable-debutant107194"},
    {title:"Des Développeurs .NET confirmé/ sénior","company":"BOCASAY","contra":"Contrat CDI","description":"\n                Garant de la veille technologique, nous serons à l’écoute de vos propositions d’évolutions. Vous interviendrez sur le développement d'applications web autour des aspects suivants : _ Développement,…            ","details":"https://www.portaljob-madagascar.com/emploi/view/bocasay54-des-developpeurs-net-confirme-senior106997"},
    {title:"DEVELOPPEURS PYTHON",company:"BOCASAY",contra:"Contrat CDI",description:"\n                Au sein d’une équipe à taille humaine rassemblant des compétences variées, dans une bonne ambiance de travail, vous développerez en équipe des solutions web à fortes valeurs ajoutées. Garant de la veille…            ",details:"https://www.portaljob-madagascar.com/emploi/view/bocasay54-developpeurs-python106996"},
    {title:"DEVELOPPEURS WORDPRESS ET PRESTASHOP -réf:DEV/0722",company:"Les Ateliers du Capricorne",contra:"Contrat CDI",description:"\n                • Développement et intégration site web sous Wordpress, Prestashop, web services et applicatifs. • Personnalisation de site web à partir de template. • Développement des modules sous Wordpress, Prestashop.…            ",details:"https://www.portaljob-madagascar.com/emploi/view/les-ateliers-du-capricorne-developpeurs-wordpess-et-prestashop-ref-dev-0722106821"},
    {title:"DEVELOPPEURS PHP -réf:DEV/07/22",company:"Les Ateliers du Capricorne",contra:"Contrat CDI",description:"\n                ‣ Développer des logiciels au sein de plateformes existantes. ‣ Respecter les bonnes pratiques de développement, build et delivery. ‣ Répondre aux besoins des clients au travers de nouvelles fonctionnalités.…            ",details:"https://www.portaljob-madagascar.com/emploi/view/les-ateliers-du-capricorne-developpeurs-php-ref-dev-07-22106850"},
    {title:"DES STAGIAIRES CHARGE(E)S RH",company:"Les Ateliers du Capricorne",contra:"Contrat Avec possibilité d'embauche",description:"\n                Avec un accompagnement par nos soins, le stagiaire aura pour mission d’apporter son appui sur trois volets: - L’administration du personnel : Gestion des dossiers du personnel, gestion des absences, gestions…            ",details:"https://www.portaljob-madagascar.com/emploi/view/les-ateliers-du-capricorne-des-stagiaires-charge-e-s-rh106849"},
    {title:"Conseiller(e)s Clientèles - réf : CCL/NIM",company:"NIM",contra:"Contrat CDI",description:"\n                Assure le conseil, la promotion et la vente des produits et services financiers de l'Institution, auprès d'une clientèle de particuliers, de professionnels, d'entreprises et de secteur…            ",details:"https://www.portaljob-madagascar.com/emploi/view/nouvelle-institution-de-microfinance-conseiller-e-s-clienteles107462"},
    {title:"CHEF DE PROJET DIGITAL",company:"ABL OUTSOURCING",contra:"Contrat CDI","description":"\n                En pleine croissance, nous recherchons UN Chef de projet DIGITAL qui va compléter notre team pour piloter, organiser et conduire les projets de bout en bout. Vos responsabilités : Comprendre les besoins…            ","details":"https://www.portaljob-madagascar.com/emploi/view/abl-outsourcing-chef-de-projet-digital107454"},
    {title:"CHARGE DE FORMATION ET QUALITE pour le Département Appel",company:"ABL OUTSOURCING",contra:"Contrat CDI",description:"\n                Formation : - Assurer la montée en compétences des nouveaux arrivants. - Former ses équipes sur la partie métier, produit et autre besoin. - Relayer les informations/ consignes de l'entreprise ou…            ",details:"https://www.portaljob-madagascar.com/emploi/view/abl-outsourcing-charge-de-formation-et-qualite-pour-le-departement-appel107452"},
    {title:"UN SUPERVISEUR CALL JUNIOR",company:"ABL OUTSOURCING",contra:"Contrat CDI",description:"\n                En pleine croissance, nous recherchons UN SUPERVISEUR CALL JUNIOR qui aura pour mission principale d’accompagner au quotidien une équipe de conseillers clients et de garantir le bon fonctionnement des…            ",details:"https://www.portaljob-madagascar.com/emploi/view/abl-outsourcing-un-superviseur-call-junior107451"},
    {title:"Responsable de Plateforme pluridisciplinaire -réf:2022/33",company:"Alliance Externe",contra:"Contrat CDI",description:"\n                Dans un contexte de croissance de notre client, nous cherchons à créer une nouvelle plateforme pluridisciplinaire pour répondre aux besoins d’une société de service basée en France. Cette société commercialise,…            ",details:"https://www.portaljob-madagascar.com/emploi/view/alliance-externe-responsable-de-plateforme-pluridisciplinaire-ref-2022-33107366"},
    {title:"Formateurs en Gestion et Création d'Entreprise (GCE) et en Bâtiment et Travaux Publics (BTP) -réf:FORMA-GCE-22 / FORMA-BTP-22 - Ambatomirahavavy-Itasy",company:"Anonyme",contra:"Contrat Vacataire",description:"\n                Sous la Responsabilité de la direction des études, les formateurs auront pour mission : 1- De Concevoir et proposer un syllabus de formation selon la directive du chef de mention 2- D’imposer une bonne…            ",details:"https://www.portaljob-madagascar.com/emploi/view/institut-superieur-d-039-ambatomirahavavy-formateurs-en-gestion-et-creation-d-entreprise-gce-et-en-batiment-et-travaux-publics-btp107057"},
    {title:"Coordinateur Agricole Grand Nord  à Nosy BE- réf : CA/GN",company:"Esanandro",contra:"Contrat CDI",description:"\n                Les responsabilités clés du.de la Coordinateur.trice Développement Agricole seront les suivantes : • Développement et mise en œuvre de la stratégie agricole ; • Coordination des technologies et approches…            ",details:"https://www.portaljob-madagascar.com/emploi/view/esanandro-coordinateur-agricole-grand-nord-a-nosy-be-ref-ca-gn107266"},
    {title:"AGENT MAILING",company:"Outsourcia Madagascar",contra:"Contrat CDI",description:"\n                - Assurer le traitement des demandes des clients de manière professionnelle : Émission d'appels, mails et/ou sms - Remonter les anomalies éventuelles rencontrées durant le traitement - Atteindre…            ",details:"https://www.portaljob-madagascar.com/emploi/view/outsourcia-madagascar-agent-mailing107077"},
    {title:"Responsable recrutement Anglophone -réf:Rh-UK",company:"Outsourcia Madagascar",contra:"Contrat CDI","description":"\n                Gestion du recrutement Elaboration de la politique de recrutement interne et externe en fonction des axes stratégiques de développement et des aspects budgétaires Prise en charge de l'intégralité…            ",details:"https://www.portaljob-madagascar.com/emploi/view/outsourcia-madagascar-responsable-recrutement-anglophone-ref-rh-uk107265"},
    {title:"Administrateur/ Ingénieur Systemes Windows",company:"AM WEB Solutions",contra:"Contrat CDI","description":"\n                Compétences Techniques Attendues: - Administration: Active Directory - Windows Server 2012, 2016, 2019 (Exigé) - Virtualisation: VMware, Hyper-V (Exigé) - Messagerie: Exchange 2010,02013,02016 (Exigé)…            ",details:"https://www.portaljob-madagascar.com/emploi/view/id-web-administrateur-ingenieur-systemes-windows106347"},
    {title:"DEVELOPER ETL TALEND",company:"AM WEB Solutions",contra:"Contrat CDI",description:"\n                Translate functional design into Technical Solution Design and create complex data conversion transformation program Conduct quality control on developments by peers (transformation programs) Prepares…            ",details:"https://www.portaljob-madagascar.com/emploi/view/id-web-developer-etl-talend106349"},
    {title:"Ingénieur d'étude et développement Fullstack ",company:"ID?WEB",contra:"Contrat CDI",description:"\n                Dans le cadre de nos activités, nous recherchons un(e) Développeur Web (F/H) Vous serez amené à : – maintenir des applications web pour nos clients – développer des plugins – Intégrer des fonctionnalités…            ",details:"https://www.portaljob-madagascar.com/emploi/view/id-web-ingenieur-d-etude-et-developpement-fullstack106350"}]
  }
    
 

}




